name: doxygen_on_push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  firmware_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the documentation
        run: |
          doxygen
