name: build_on_push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  firmware_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Fetch submodules
        run: |
          git submodule update --init
          git -C pico-sdk submodule update --init

      - name: Build each example on every commit
        run: |
          for example in example/pico-*; do
            mkdir -p $example/build
            cd $example/build
            cmake ..
            make
            cd -
          done
